from __future__ import annotations
from pathlib import Path
from datetime import datetime, timezone
import html, json, re, xml.etree.ElementTree as ET

try:
    from markitdown import MarkItDown
except Exception:
    MarkItDown = None

try:
    import markdown as markdown_lib
except Exception:
    markdown_lib = None

try:
    from bs4 import BeautifulSoup
except Exception:
    BeautifulSoup = None

TEXT_EXTS = {".md", ".markdown", ".ash", ".html", ".htm", ".html5", ".txt", ".xml", ".json"}

def detect_format(path: Path) -> str:
    ext = path.suffix.lower()
    if ext in {".md", ".markdown"}:
        return "md"
    if ext in {".html", ".htm", ".html5"}:
        return "html5" if ext == ".html5" else "html"
    if ext == ".ash":
        return "ash"
    if ext == ".xml":
        return "xml"
    if ext == ".json":
        return "json"
    return "txt"

def _html_to_markdown(path: Path, text: str) -> str:
    if MarkItDown is not None:
        try:
            result = MarkItDown(enable_plugins=False).convert_local(str(path))
            md = getattr(result, "markdown", None) or getattr(result, "text_content", None)
            if md:
                return md
        except Exception:
            pass
    if BeautifulSoup is not None:
        soup = BeautifulSoup(text, "html.parser")
        for tag in soup(["script", "style"]):
            tag.decompose()
        return soup.get_text("\n", strip=True)
    return re.sub(r"<[^>]+>", "", text)

def to_markdown(path: Path, text: str, fmt: str) -> str:
    if fmt == "md":
        return text
    if fmt == "txt":
        return text
    if fmt == "ash":
        return f"```ash\n{text.rstrip()}\n```\n"
    if fmt in {"html", "html5"}:
        return _html_to_markdown(path, text)
    if fmt == "json":
        try:
            obj = json.loads(text)
            rendered = json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True)
        except Exception:
            rendered = text
        return f"```json\n{rendered.rstrip()}\n```\n"
    if fmt == "xml":
        return f"```xml\n{text.rstrip()}\n```\n"
    return text

def markdown_to_plain(md: str) -> str:
    s = re.sub(r"```[A-Za-z0-9_-]*\n?", "", md)
    s = s.replace("```", "")
    s = re.sub(r"!\[([^\]]*)\]\([^)]+\)", r"\1", s)
    s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)
    s = re.sub(r"^\s{0,3}#{1,6}\s+", "", s, flags=re.M)
    s = re.sub(r"^\s*[-*+]\s+", "", s, flags=re.M)
    s = re.sub(r"^\s*\d+\.\s+", "", s, flags=re.M)
    s = re.sub(r"[*_~`]", "", s)
    return s.strip() + "\n"

def _render_html5(md: str, title: str, source: str) -> str:
    if markdown_lib is not None:
        body = markdown_lib.markdown(md, extensions=["tables", "fenced_code"])
    else:
        body = "<pre>" + html.escape(md) + "</pre>"
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<style>
:root{{color-scheme:dark;--bg:#10100e;--paper:#ffffe3;--muted:#9a9a87;--line:#37372f}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--paper);font:16px/1.55 Georgia,serif}}
main{{max-width:980px;margin:auto;padding:48px 30px 80px}}header{{border-bottom:1px solid var(--line);margin-bottom:28px}}
.meta{{font:12px ui-monospace,monospace;color:var(--muted)}}pre,code{{font-family:ui-monospace,monospace}}pre{{overflow:auto;border:1px solid var(--line);padding:16px}}
table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid var(--line);padding:8px;text-align:left}}a{{color:inherit}}
</style></head>
<body><main><header><h1>{html.escape(title)}</h1><p class="meta">generated by kol-doc-edit · source {html.escape(source)}</p></header>
<article class="doc-edit-document">{body}</article></main></body></html>
"""

def from_markdown(md: str, target_fmt: str, source_path: str, *, original_text: str = "", source_fmt: str = "") -> str:
    now = datetime.now(timezone.utc).isoformat()
    if target_fmt == "md":
        return md
    if target_fmt == "txt":
        return markdown_to_plain(md)
    if target_fmt in {"html", "html5"}:
        return _render_html5(md, Path(source_path).name or "doc-edit", source_path)
    if target_fmt == "json":
        return json.dumps({
            "schema": "kol-doc-edit/document-v1",
            "generated_at": now,
            "source": source_path,
            "markdown": md,
            "plain_text": markdown_to_plain(md)
        }, indent=2, ensure_ascii=False) + "\n"
    if target_fmt == "xml":
        root = ET.Element("doc-edit-document", {"schema": "v1"})
        ET.SubElement(root, "generated-at").text = now
        ET.SubElement(root, "source").text = source_path
        ET.SubElement(root, "markdown").text = md
        ET.SubElement(root, "plain-text").text = markdown_to_plain(md)
        return ET.tostring(root, encoding="unicode") + "\n"
    if target_fmt == "ash":
        if source_fmt == "ash":
            return original_text
        # Deliberately non-executable container: prose converted to .ash becomes comments.
        lines = markdown_to_plain(md).splitlines()
        payload = "\n".join(" * " + line.replace("*/", "* /") for line in lines)
        return "/* DOC-EDIT DOCUMENT CONTAINER — NON-EXECUTABLE CONTENT\n" + payload + "\n */\n"
    return md

def convert_text(source: Path, target: Path) -> tuple[str, dict]:
    source_fmt = detect_format(source)
    target_fmt = detect_format(target)
    if source.suffix.lower() not in TEXT_EXTS:
        raise ValueError(f"unsupported source extension: {source.suffix}")
    if target.suffix.lower() not in TEXT_EXTS:
        raise ValueError(f"unsupported target extension: {target.suffix}")
    text = source.read_text(encoding="utf-8", errors="replace")
    md = to_markdown(source, text, source_fmt)
    out = from_markdown(md, target_fmt, str(source), original_text=text, source_fmt=source_fmt)
    return out, {"source_format": source_fmt, "target_format": target_fmt, "markdown_chars": len(md), "output_chars": len(out)}
